default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: leitura_do_lugar_development

test:
  <<: *default
  database: leitura_do_lugar_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
